cultuurnet/widget-beheer-angular

src/app/app.module.ts, src/app/page-templates/my-template.ts, src/app/shared/pageTemplate.ts, src/app/shared/services/page-template-registry.service.ts, src/app/shared/services/widget-type-registry.service.ts, src/app/widget-builder/widget-builder.component.ts
=> feature/WID-13: As developer, I can easily add new templates

src/app/core/layout/components/abstract-layout.component.ts, src/app/widget-builder/components/layouts/2col-sidebar-left/2col-sidebar-left-layout.component.ts, src/app/widget-builder/components/layouts/2col-sidebar-left/2col-sidebar-left.component.html, src/app/widget-builder/components/layouts/2col-sidebar-right/2col-sidebar-right-layout.component.ts, src/app/widget-builder/components/layouts/2col-sidebar-right/2col-sidebar-right.component.html, src/app/widget-builder/components/layouts/3col-double-sidebar/3col-double-sidebar-layout.component.ts, src/app/widget-builder/components/layouts/3col-double-sidebar/3col-double-sidebar.component.html, src/app/widget-builder/components/layouts/full-width/full-width-layout.component.ts, src/app/widget-builder/components/layouts/full-width/full-width.component.html, src/app/widget-builder/components/widgets/widget-preview.component.html, src/app/widget-builder/components/widgets/widget-preview.component.ts, src/app/widget-builder/widget-builder.module.ts, src/assets/i18n/nl.json
=> Feature/WID-18: As widget builder, I can delete a widget

src/app/widget-builder/components/widgets/base-widget-edit.component.ts, src/app/widget-builder/components/widgets/html-widget/html-widget-edit.component.ts
- added extra check for values.genaral in base widget component
- apply content.body setting to formbuilder
=> WID-222 - fix issue with ckeditor in HTML widgetbuilder

.github/pull_request_template.md
- pull request template, same as udb3
=> add pull-request template

src/app/widget-builder/components/widgets/search-results-widget/search-results-widget-edit.component.html
- removed the `beta` badge 
---
Ticket: [https://jira.uitdatabank.be/browse/WID-252](https://jira.uitdatabank.be/browse/WID-252)
=> WID-252 - removed beta badge

src/app/widget-builder/components/widgets/search-results-widget/search-results-widget-edit.component.html
- fixed missing span
---
Ticket: [https://jira.uitdatabank.be/browse/WID-205](https://jira.uitdatabank.be/browse/WID-205)
=> WID-252 - fix missing span

src/app/widget-builder/components/widgets/search-results-widget/search-results-widget-edit.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.ts
- added indiestyle as a publisher
- load publishers from env config file
---
Ticket: [https://jira.uitdatabank.be/browse/III-3098](https://jira.uitdatabank.be/browse/III-3098)
=> III-3098 - added indiestyle as a publisher

src/environments/environment.jenkins.ts
- key for publishers + hash for jenkins config
=> III-3098 - added publishers key + hash to jenkins config

src/app/widget-builder/components/widgets/search-results-widget/search-results-widget-edit.component.ts, src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.ts
- get publisher string from config and transform it into array
=> III-3098 - get publisher string from config and transform it into array

src/app/widget-builder/components/theme-edit/themes.ts
Fixed path of bill preview image
---
Ticket: [https://jira.uitdatabank.be/browse/WID-255](https://jira.uitdatabank.be/browse/WID-255)
=> change path of image

src/app/app.component.html, src/index.html, src/styles/02_components/_widget-loader.scss
- removed text from loader
- removed redundant comment
---
Ticket: [https://jira.uitdatabank.be/browse/WID-292](https://jira.uitdatabank.be/browse/WID-292)
=> WID-292 - remove loader + remove redundant comment

src/app/core/template/page-templates/uitpas-page-template.ts
-  link facets filters with searchresults
---
Ticket: [https://jira.uitdatabank.be/browse/WID-283](https://jira.uitdatabank.be/browse/WID-283)
=> WID-283 - link facets filters with searchresults

src/app/core/template/page-templates/uitpas-page-template.ts
- replace links for UiTPAS template
---
Ticket: [https://jira.uitdatabank.be/browse/WID-234](https://jira.uitdatabank.be/browse/WID-234)
=> WID-234 - replace links for UiTPAS template

src/app/widget-builder/components/widgets/search-results-widget/search-results-widget-edit.component.html, src/app/widget-builder/components/widgets/search-results-widget/search-results-widget-edit.component.ts
- added new setting for editorial label in list items of search results
---
Ticket: [https://jira.uitdatabank.be/browse/WID-317](https://jira.uitdatabank.be/browse/WID-317)
=> WID-317 - added new setting for editorial label in search results

src/environments/environment.dev.ts, src/environments/environment.prod.ts, src/environments/environment.ts
- Update publishers
---
Ticket: https://jira.uitdatabank.be/browse/WID-360
=> WID-360 Update publishers

src/app/widget-builder/components/theme-edit/themes.ts
- Change styling copy for retro look after UiT rebranding
---
Ticket: https://jira.uitdatabank.be/browse/WID-388
=> WID-388 Change styling copy

src/app/widget-builder/components/toolbar/toolbar.component.html, src/app/widget-builder/components/toolbar/toolbar.component.ts, src/app/widget-builder/components/widgets/widget-preview.component.html
- Change icon for "move" arrows
- Change icons for view modes
---
Ticket: https://jira.uitdatabank.be/browse/WID-395
=> WID-395 Fontawesome tweaks

src/app/widget-builder/widget-builder.component.ts
- Fixed the drag and drop of widgets that got broken by changing the arrow class
---
Ticket: https://jira.uitdatabank.be/browse/WID-439
=> WID-439 Fix the drag and drop that got broken by changing the arrow class

tsconfig.json
- javascript target
---
Ticket: https://jira.uitdatabank.be/browse/WID-325
=> WID-325 - Change target to ES5 so that env variables script doesn't fail

src/assets/config.json, src/environments/environment.ts, src/main.ts
- casing variables
- everything hopefully
---
Ticket: https://jira.uitdatabank.be/browse/WID-454
=> Feature/WID-454 - runtime vars

src/app/core/widget/widget-page.ts
- removeWidget code
---
Ticket: https://jira.uitdatabank.be/browse/WID-526
=> WID-526 - Fix removeWidget code

src/assets/i18n/nl.json
* link to new docs instead of old docs
---
Ticket:https://jira.uitdatabank.be/browse/WID-537
=> Change link to new docs

src/app/core/route/guard/auth-guard.service.ts, src/app/core/topbar/components/topbar.component.html, src/app/core/topbar/components/topbar.component.ts
- Redirect with back button to publiq-platform when publiq-platform is live
- Remove logout button when publiq-platform is live
---
Ticket: https://jira.publiq.be/browse/PPF-237
=> PPF-237 redirect to public platform

src/app/core/topbar/components/topbar.component.ts, src/environments/environment.ts
- [missing env vars](https://github.com/cultuurnet/widget-beheer-angular/commit/20fb6a46febb09c73666677b6749d1813ef97241)
- [change `platformIsLive` to a public var](https://github.com/cultuurnet/widget-beheer-angular/commit/6fc6a233856ef6c43d6de18607409b3e800bc13c)
---
Ticket: https://jira.publiq.be/browse/PPF-237
=> PPF-237 - build fix

src/app/core/template/page-templates/uitpas-page-template.ts, src/app/page.json
- Set icon_uitx to default false
---
Ticket: https://jira.publiq.be/browse/WID-568
=> WID-568 - Set icon_uitx to default false

src/assets/i18n/nl.json
=> Fix back button copy
